version: 2.1

workflows:
  building:
    jobs:
      - run_tests

jobs:
  run_tests:
    docker:
      - image: quay.io/haskell_works/ghc-8.6.5:i386-ubuntu-18.04
    working_directory: ~/project
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependeces-{{ checksum "./build/project.summary" }}
      - run:
          name: init cabal
          command: |
            if [[ ! -e ~/.cabal/config ]]; then
              cabal user-config init
            fi
            echo >> ~/.cabal/config
            echo    "http-transport: wget"                                 >> ~/.cabal/config
            echo    "repository private"                                   >> ~/.cabal/config
            echo -n "  url: https://<< parameters.private-hackage-user >>" >> ~/.cabal/config
            echo -n ":<< parameters.private-hackage-password >>"           >> ~/.cabal/config
            echo    "@<< parameters.private-hackage-domain >>/"            >> ~/.cabal/config
            echo    "  secure: True"                                       >> ~/.cabal/config
            echo    "  root-keys: << parameters.private-hackage-keys >>"   >> ~/.cabal/config
            echo    "  key-threshold: 2"                                   >> ~/.cabal/config
      - run:
          name: build-libs
          command: |
            cabal v2-install --reorder-goals --max-backjumps=-1
      - run:
          name: test
          command: cabal new-test
      - run:
          name: make-cachefile
          command: |
            mkdir -p ./build
            find . -name "*.cabal" | grep -v 'dist-newstyle/' | sort | xargs grep '^' | grep -v ':version:' | md5sum > ./build/project.summary
      - save_cache:
          key: dependeces-{{ checksum "./build/project.summary" }}
          paths: 
            - build
