version: 2.1

orbs:
  haskell-build: haskell-works/haskell-build@4.1.9
workflows:
  build-app:
    jobs:
      - cabal-build-extra:
        executor: haskell/ghc-8_6_5
        name: GHC8.4.4
      - cabal-test-extra:
        requires:
        - cabal-build-extra
