version: 2.1

workflows:
  building:
    jobs:
      - run_tests

jobs:
  run_tests:
    docker:
      - image: quay.io/haskell_works/ghc-8.10.1:i386-ubuntu-18.04
    working_directory: ~/project
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependeces-{{ checksum "~/.cabal/project.summary" }}
      - run:
          name: init cabal
          command: |
            if [[ ! -e ~/.cabal/config ]]; then
              cabal user-config init
            fi
            cabal user-config update
            cabal update
      - run:
          name: build-libs
          command: |
            cabal v2-install --reorder-goals --max-backjumps=-1
      - run:
          name: test
          command: cabal new-test
      - run:
          name: make-cachefile
          command: |
            touch ~/.cabal/project.summary
            find . -name "*.cabal" | grep -v 'dist-newstyle/' | sort | xargs grep '^' | grep -v ':version:' | md5sum > ~/.cabal/project.summary
      - save_cache:
          key: v2-dependeces-{{ checksum "~/.cabal/project.summary" }}
          paths: 
            - ~/.cabal
