version: 2.1

workflows:
  building:
    jobs:
      - run_tests

jobs:
  run_tests:
    docker:
      - image: quay.io/haskell_works/ghc-8.6.3:ubuntu-16.04
    working_directory: ~/project
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependeces-{{ checksum "./build/project.summary" }}
      - run:
          name: build-libs
          command: |
            cabal cabal v2-install --reorder-goals --max-backjumps=-1
      - run:
          name: test
          command: cabal new-test
      - run:
          name: make-cachefile
          command: |
            mkdir -p ./build
            find . -name "*.cabal" | grep -v 'dist-newstyle/' | sort | xargs grep '^' | grep -v ':version:' | md5sum > ./build/project.summary
      - save_cache:
          key: dependeces-{{ checksum "./build/project.summary" }}
          paths: 
            - build
